export const REQUEST_SCHOOLS_BY_LEVELS = "REQUEST_SCHOOLS_BY_LEVELS"
export const REQUEST_SCHOOLS_BY_SCHOOLTYPE = "REQUEST_SCHOOLS_BY_SCHOOLTYPE"
export const REQUEST_SCHOOLS_BY_DISTRICT = "REQUEST_SCHOOLS_BY_DISTRICT"
export const REQUEST_SCHOOLS_BY_STATUS = "REQUEST_SCHOOLS_BY_STATUS"
export const REQUEST_SCHOOLS_BY_SEARCH = "REQUEST_SCHOOLS_BY_SEARCH"

export const GET_SCHOOLS = "GET_SCHOOLS"
