export const data = [
    {
      id: 1,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 2,
      schoolName: 'Trần Khánh Dư',
      type: 'Công lập',
      district: '1',
      address: '105 Nguyễn Thái Bình, P.Nguyễn Thái Bình ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 3,
      schoolName: 'Đuốc Sống',
      type: 'Công lập',
      district: '3',
      address: '44 Phó Đức Chính, P.Nguyễn Thái Bình ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 4,
      schoolName: 'Đinh Tiên Hoàng',
      type: 'Công lập',
      district: '4',
      address: '2B Lương Hữu Khánh, P.Phạm Ngũ Lão ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Cũ',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 5,
      schoolName: 'Nguyễn Bỉnh Khiêm',
      type: 'Công lập',
      district: '6',
      address: '93 - 95 A Lê Thị Riêng, P.Bến Thành ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Cũ',
      level: 'Trung học cơ sở',
      action: '',
    },
    {
      id: 6,
      schoolName: 'Hòa Bình',
      type: 'Công lập',
      district: '5',
      address: '71 Trần Hưng Đạo, P.Cầu Ông Lãnh ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Cũ',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 7,
      schoolName: 'Kết Đoàn',
      type: 'Công lập',
      district: '7',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 8,
      schoolName: 'Lương Thế Vinh',
      type: 'Công lập',
      district: '3',
      address: '67 Đinh Tiên Hoàng, P.Đa Kao  ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 9,
      schoolName: 'Khai Minh',
      type: 'Công lập',
      district: '1',
      address: '181 Hoàng Sa, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 10,
      schoolName: 'Nguyễn Thái Bình',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học cơ sở',
      action: '',
    },
    {
      id: 11,
      schoolName: 'Nguyễn Huệ',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 12,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 13,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 14,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học cơ sở',
      action: '',
    },
    {
      id: 15,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 16,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
    {
      id: 17,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Cũ',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 18,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 19,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học cơ sở',
      action: '',
    },
    {
      id: 20,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Trung học cơ sở',
      action: '',
    },
    {
      id: 21,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Cũ',
      level: 'Trung học phổ thông',
      action: '',
    },
    {
      id: 22,
      schoolName: 'Trần Quang Khải',
      type: 'Công lập',
      district: '1',
      address: '68/29B Trần Quang Khải, P.Tân Định ',
      contact: '038484288',
      representor: 'Hồ Quang Tuấn',
      status: 'Mới',
      level: 'Tiểu học',
      action: '',
    },
  ]